version: "3.5"

networks:
        localhost:
                name: net

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/prranges/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/prranges/data/mariadb
                        o: bind
                        type: none
        website:
                name: website
                driver: local
                driver_opts:
                        device: /home/prranges/data/html
                        o: bind
                        type: none
        portainer_data:
                name: portainer_data
                driver: local
                driver_opts:
                        device: /home/prranges/data/portainer
                        o: bind
                        type: none


services:
        nginx:
                depends_on:
                        - wordpress
                container_name: nginx
                build: ./requirements/nginx
                image: nginx
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/var/www/wordpress
                        - website:/var/www/html
                networks:
                        - localhost
                restart: always
        mariadb:  
                container_name: mariadb
                build: ./requirements/mariadb
                env_file: .env
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - localhost
                image: mariadb
                restart: always
        wordpress:
                depends_on:
                        - mariadb
                container_name: wordpress
                build: ./requirements/wordpress
                env_file: .env
                image: wordpress
                ports:
                        - "9000:9000"
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - localhost
                restart: always
        ftp-server:
                container_name: ftp-server
                build: ./requirements/bonus/ftp-server
                image: ftp-server
                ports:
                        - "21:21"
                        - "10100-10110:10100-10110"
                volumes:
                        - /home/prranges/data:/var/www/ftp
                networks:
                        - localhost
                restart: always
                env_file: .env
        portainer:
                container_name: portainer
                build: ./requirements/bonus/portainer
                image: portainer
                ports:
                        - "8000:9000"
                        - "9443:9443"
                volumes:
                        - /etc/localtime:/etc/localtime
                        - portainer_data:/data
                        - /var/run/docker.sock:/var/run/docker.sock
                networks:
                        - localhost
                restart: always
        adminer:
                container_name: adminer
                build: ./requirements/bonus/adminer
                depends_on:
                        - mariadb
                image: adminer
                restart: always
                ports:
                        - 8080:8080
                networks:
                        - localhost
        redis:
                container_name: redis
                build: ./requirements/bonus/redis
                image: redis
                ports:
                        - "6379:6379"
                networks:
                        - localhost
                restart: always